# Generated by Django 3.1.2 on 2023-11-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20231116_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
