# Generated by Django 3.1.2 on 2023-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20231116_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='is_main',
        ),
        migrations.AddField(
            model_name='connections',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
