# Generated by Django 3.1.2 on 2023-11-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20231116_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='connections',
            old_name='type',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.AddField(
            model_name='article',
            name='Tag',
            field=models.ManyToManyField(through='articles.Connections', to='articles.Tag'),
        ),
    ]
