# Generated by Django 3.1.2 on 2023-11-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20231116_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Scope',
        ),
    ]
